// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ai-configs": {
            "get": {
                "description": "获取当前用户的所有AI配置（已废弃，请使用 /api/app/friends/bots）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI配置管理（已废弃）"
                ],
                "summary": "获取用户AI配置列表（已废弃）",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的AI配置（已废弃，请使用 /api/v2/bots + /api/app/friends/bots）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI配置管理（已废弃）"
                ],
                "summary": "创建AI配置（已废弃）",
                "deprecated": true,
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateAIConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/ai-configs/{id}": {
            "get": {
                "description": "根据配置ID获取配置详情（已废弃）",
                "tags": [
                    "AI配置管理（已废弃）"
                ],
                "summary": "获取配置详情（已废弃）",
                "deprecated": true,
                "responses": {}
            },
            "put": {
                "summary": "更新AI配置（已废弃）",
                "deprecated": true,
                "responses": {}
            },
            "delete": {
                "summary": "删除AI配置（已废弃）",
                "deprecated": true,
                "responses": {}
            }
        },
        "/api/ai-configs/{id}/priority": {
            "patch": {
                "summary": "设置配置优先级（已废弃）",
                "deprecated": true,
                "responses": {}
            }
        },
        "/api/ai-configs/{id}/toggle": {
            "patch": {
                "summary": "切换配置状态（已废弃）",
                "deprecated": true,
                "responses": {}
            }
        },
        "/api/app/friends/bots": {
            "get": {
                "description": "获取用户的所有Bot好友",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户好友管理"
                ],
                "summary": "获取Bot好友列表",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "添加Bot为好友",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户好友管理"
                ],
                "summary": "添加Bot好友",
                "parameters": [
                    {
                        "description": "好友信息",
                        "name": "friend",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddBotFriendRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "添加成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/app/friends/bots/{bot_config_id}": {
            "delete": {
                "description": "删除Bot好友关系",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户好友管理"
                ],
                "summary": "删除Bot好友",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bot配置ID",
                        "name": "bot_config_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "好友不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/app/friends/bots/{bot_config_id}/appkey": {
            "patch": {
                "description": "更新Bot好友的LLM API密钥",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户好友管理"
                ],
                "summary": "更新Bot好友的AppKey",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bot配置ID",
                        "name": "bot_config_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AppKey信息",
                        "name": "appkey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateBotFriendAppKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "好友不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/app/friends/bots/{bot_config_id}/priority": {
            "patch": {
                "description": "更新Bot好友的优先级",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户好友管理"
                ],
                "summary": "更新Bot好友优先级",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bot配置ID",
                        "name": "bot_config_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "优先级信息",
                        "name": "priority",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateBotFriendPriorityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "好友不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/app/friends/bots/{bot_config_id}/toggle": {
            "patch": {
                "description": "启用或禁用Bot好友",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户好友管理"
                ],
                "summary": "切换Bot好友状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bot配置ID",
                        "name": "bot_config_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "状态信息",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ToggleBotFriendStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "好友不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v2/bots": {
            "post": {
                "description": "创建新的Bot配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot配置管理"
                ],
                "summary": "创建Bot配置",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateBotConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v2/bots/my": {
            "get": {
                "description": "获取当前用户创建的所有Bot配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot配置管理"
                ],
                "summary": "获取我创建的Bot列表",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v2/bots/search": {
            "get": {
                "description": "搜索Bot配置，支持bot_hash精确搜索和bot_name模糊搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot配置管理"
                ],
                "summary": "搜索Bot配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索类型：hash/name/description，默认为name",
                        "name": "search_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v2/bots/{id}": {
            "get": {
                "description": "根据ID获取Bot配置详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot配置管理"
                ],
                "summary": "获取Bot配置详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bot配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定的Bot配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot配置管理"
                ],
                "summary": "更新Bot配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bot配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateBotConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定的Bot配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot配置管理"
                ],
                "summary": "删除Bot配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bot配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v2/models": {
            "get": {
                "description": "获取模型配置列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型配置管理"
                ],
                "summary": "获取模型配置列表",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "是否只包含公共模型",
                        "name": "include_public",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的模型配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型配置管理"
                ],
                "summary": "创建模型配置",
                "parameters": [
                    {
                        "description": "模型配置信息",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v2/models/{id}": {
            "get": {
                "description": "根据ID获取模型配置详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型配置管理"
                ],
                "summary": "获取模型配置详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "模型配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定的模型配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型配置管理"
                ],
                "summary": "更新模型配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "模型配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定的模型配置（软删除）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模型配置管理"
                ],
                "summary": "删除模型配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "模型配置ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/device/bind": {
            "post": {
                "description": "绑定设备到用户账户，生成设备密钥和token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Device"
                ],
                "summary": "设备绑定",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cUserJWT\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设备绑定请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/device.BindDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "绑定成功",
                        "schema": {
                            "$ref": "#/definitions/device.BindDeviceResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/device.BindDeviceResponse"
                        }
                    },
                    "401": {
                        "description": "认证失败",
                        "schema": {
                            "$ref": "#/definitions/device.BindDeviceResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/device.BindDeviceResponse"
                        }
                    }
                }
            }
        },
        "/device/refresh_token": {
            "get": {
                "description": "刷新设备的JWT token，延长有效期",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Device"
                ],
                "summary": "刷新设备token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前设备token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "设备绑定密钥",
                        "name": "bind_key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "$ref": "#/definitions/device.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/device.RefreshTokenResponse"
                        }
                    },
                    "401": {
                        "description": "认证失败",
                        "schema": {
                            "$ref": "#/definitions/device.RefreshTokenResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/device.RefreshTokenResponse"
                        }
                    }
                }
            }
        },
        "/device/unbind": {
            "post": {
                "description": "解绑指定设备，将数据库中is_active字段设置为false",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Device"
                ],
                "summary": "设备解绑",
                "parameters": [
                    {
                        "description": "设备解绑请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/device.UnbindDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "解绑成功",
                        "schema": {
                            "$ref": "#/definitions/device.UnbindDeviceResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/device.UnbindDeviceResponse"
                        }
                    },
                    "404": {
                        "description": "设备未找到",
                        "schema": {
                            "$ref": "#/definitions/device.UnbindDeviceResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/device.UnbindDeviceResponse"
                        }
                    }
                }
            }
        },
        "/ota/": {
            "post": {
                "description": "设备上传信息后，返回最新固件版本和下载地址",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OTA"
                ],
                "summary": "上传设备信息获取最新固件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ota.OTARequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ota.OTAResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "device.BindDeviceRequest": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string"
                }
            }
        },
        "device.BindDeviceResponse": {
            "type": "object",
            "properties": {
                "device_key": {
                    "description": "设备长期密钥S（明文，仅下发一次）",
                    "type": "string"
                },
                "message": {
                    "description": "错误信息（失败时）",
                    "type": "string"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                },
                "token": {
                    "description": "30天有效期DeviceToken（成功时）",
                    "type": "string"
                }
            }
        },
        "device.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "device.UnbindDeviceRequest": {
            "type": "object",
            "required": [
                "bind_key",
                "device_id"
            ],
            "properties": {
                "bind_key": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                }
            }
        },
        "device.UnbindDeviceResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.AddBotFriendRequest": {
            "type": "object",
            "required": [
                "app_key",
                "bot_config_id"
            ],
            "properties": {
                "alias": {
                    "type": "string"
                },
                "app_key": {
                    "type": "string"
                },
                "bot_config_id": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer"
                }
            }
        },
        "models.CreateAIConfigRequest": {
            "type": "object",
            "required": [
                "config_name",
                "function_name"
            ],
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "config_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "function_name": {
                    "description": "不能为空，且长度必须大于0",
                    "type": "string",
                    "minLength": 1
                },
                "llm_type": {
                    "type": "string"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "mcp_server_url": {
                    "type": "string"
                },
                "model_name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "priority": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "models.CreateBotConfigRequest": {
            "type": "object",
            "required": [
                "config_name",
                "description",
                "function_name",
                "model_id"
            ],
            "properties": {
                "config_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "function_name": {
                    "type": "string",
                    "minLength": 1
                },
                "max_tokens": {
                    "type": "integer"
                },
                "mcp_server_url": {
                    "type": "string"
                },
                "model_id": {
                    "type": "integer"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "temperature": {
                    "type": "number"
                },
                "visibility": {
                    "description": "private/public",
                    "type": "string"
                }
            }
        },
        "models.ToggleBotFriendStatusRequest": {
            "type": "object",
            "required": [
                "is_active"
            ],
            "properties": {
                "is_active": {
                    "type": "boolean"
                }
            }
        },
        "models.UpdateAIConfigRequest": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "base_url": {
                    "type": "string"
                },
                "config_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "function_name": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "llm_type": {
                    "type": "string"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "mcp_server_url": {
                    "type": "string"
                },
                "model_name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "priority": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "models.UpdateBotConfigRequest": {
            "type": "object",
            "properties": {
                "config_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "function_name": {
                    "type": "string"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "mcp_server_url": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                },
                "temperature": {
                    "type": "number"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "models.UpdateBotFriendAppKeyRequest": {
            "type": "object",
            "required": [
                "app_key"
            ],
            "properties": {
                "app_key": {
                    "type": "string"
                }
            }
        },
        "models.UpdateBotFriendPriorityRequest": {
            "type": "object",
            "required": [
                "priority"
            ],
            "properties": {
                "priority": {
                    "type": "integer"
                }
            }
        },
        "ota.Activation": {
            "type": "object",
            "properties": {
                "challenge": {
                    "description": "用于设备认证挑战",
                    "type": "string"
                },
                "code": {
                    "type": "string",
                    "example": "543091"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "ota.FirmwareInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "/ota_bin/1.2.4.bin"
                },
                "version": {
                    "type": "string",
                    "example": "1.2.4"
                }
            }
        },
        "ota.MQTTInfo": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "CGID_test@@@mac@@@client"
                },
                "endpoint": {
                    "type": "string",
                    "example": "mqtt://broker:1883"
                },
                "password": {
                    "type": "string",
                    "example": "randomPwd"
                },
                "publish_topic": {
                    "type": "string",
                    "example": "device-server"
                },
                "subscribe_topic": {
                    "type": "string",
                    "example": "null"
                },
                "username": {
                    "type": "string",
                    "example": "base64string"
                }
            }
        },
        "ota.OTARequestBody": {
            "type": "object",
            "properties": {
                "application": {
                    "type": "object",
                    "properties": {
                        "compile_time": {
                            "type": "string"
                        },
                        "elf_sha256": {
                            "type": "string"
                        },
                        "idf_version": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "version": {
                            "type": "string"
                        }
                    }
                },
                "board": {
                    "type": "object",
                    "properties": {
                        "channel": {
                            "type": "integer"
                        },
                        "ip": {
                            "type": "string"
                        },
                        "mac": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "rssi": {
                            "type": "integer"
                        },
                        "ssid": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        }
                    }
                },
                "chip_info": {
                    "type": "object",
                    "properties": {
                        "cores": {
                            "type": "integer"
                        },
                        "features": {
                            "type": "integer"
                        },
                        "model": {
                            "type": "integer"
                        },
                        "revision": {
                            "type": "integer"
                        }
                    }
                },
                "chip_model_name": {
                    "type": "string"
                },
                "flash_size": {
                    "type": "number"
                },
                "language": {
                    "type": "string"
                },
                "mac_address": {
                    "type": "string"
                },
                "minimum_free_heap_size": {
                    "type": "string"
                },
                "ota": {
                    "type": "object",
                    "properties": {
                        "label": {
                            "type": "string"
                        }
                    }
                },
                "partition_table": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "address": {
                                "type": "number"
                            },
                            "label": {
                                "type": "string"
                            },
                            "size": {
                                "type": "number"
                            },
                            "subtype": {
                                "type": "integer"
                            },
                            "type": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "uuid": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "ota.OTAResponse": {
            "type": "object",
            "properties": {
                "activation": {
                    "$ref": "#/definitions/ota.Activation"
                },
                "firmware": {
                    "$ref": "#/definitions/ota.FirmwareInfo"
                },
                "mqtt": {
                    "$ref": "#/definitions/ota.MQTTInfo"
                },
                "server_time": {
                    "$ref": "#/definitions/ota.ServerTimeInfo"
                },
                "websocket": {
                    "$ref": "#/definitions/ota.WebSocketInfo"
                }
            }
        },
        "ota.ServerTimeInfo": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "integer",
                    "example": 1720065289451
                },
                "timezone_offset": {
                    "type": "integer",
                    "example": 480
                }
            }
        },
        "ota.WebSocketInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "wss://your-server/ws"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "怒喵 API 文档",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
